### ISSUE TITLE
Can't read Problem Instance 10 (Inventory Problem with Lead Time)

### ISSUE THREAD

**Issue by jk27182** [bonnkleiford/MSPLib-Library#8]
Hi,

first of all, thank you for this nice collection of problems.

I ran into some problems reading problem instance 10, I get the following error:
`ERROR: AssertionError: term["stage"] == stage - 1`.
It occurs on all problem instances, for every discretization.

**Comment by odow** [comment]
Since this error looks like Julia, I assume you're calling via SDDP.jl?

If so, please close this issue and open an issue over at https://github.com/odow/SDDP.jl/issues instead.

**Comment by jk27182** [comment]
Yes, the error occurred using SDDP.jl. I reopened the issue [here](https://github.com/odow/SDDP.jl/issues/785)
